version: '3'
services:
    product-service:
        restart: always
        container_name: product-service
        hostname: product-service
        build:
            context: ./product-service
            dockerfile: deployment/Dockerfile
        ports:
            - 8081:8081
        links:
            - product-service-db
            - auth-service
            - eureka
        depends_on:
            - product-service-db
            - auth-service
            - eureka
    price-service:
        restart: always
        container_name: price-service
        hostname: price-service
        build:
            context: ./price-service
            dockerfile: deployment/Dockerfile
        ports:
            - 8082:8082
        links:
            - price-service-db
            - auth-service
            - eureka
        depends_on:
            - price-service-db
            - auth-service
            - eureka
    auth-service:
        restart: always
        container_name: auth-service
        hostname: auth-service
        build:
            context: ./auth-service
            dockerfile: deployment/Dockerfile
        ports:
            - 9999:9999
        links:
            - eureka
        depends_on:
            - eureka
    product-service-db:
        restart: always
        container_name: product-service-db
        image: mysql
        expose:
            - "3306"
        volumes:
            - ./product-service/deployment/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product_service
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    price-service-db:
        restart: always
        container_name: price-service-db
        image: mysql
        expose:
            - "3306"
        volumes:
            - ./price-service/deployment/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: price_service
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    eureka:
        restart: always
        container_name: eureka
        hostname: eureka
        build:
            context: ./eureka-service
            dockerfile: deployment/Dockerfile
        expose:
            - "8761"
        ports:
            - 8761:8761