spring:
  application:
    name: gateway-service
  profiles:
    active: local

server:
  port: 8765
  context-path: /gateway

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/me

zuul:
  routes:
    auth:
      path: /auth-service/**
      sensitiveHeaders:
      serviceId: auth-service
    product:
      path: /product-service/**
      sensitiveHeaders:
      serviceId: product-service
    price:
      path: /price-service/**
      sensitiveHeaders:
      serviceId: price-service
  add-host-header: true

---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/