spring:
  application:
    name: order-service
  profiles:
    active: local

server:
  port: 8084

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/me

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

---
spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/order_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://product-service-db:3306/order_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/