spring:
  application:
    name: product-service
  profiles:
    active: local

server:
  port: 8081
  session:
    cookie:
      name: PRODUCT_SESSION

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

---
spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/product_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

#security:
#  oauth2:
#    client:
#      client-id: shopify
#      client-secret: shopify
#      access-token-uri: http://localhost:9999/oauth/token
#      user-authorization-uri: http://localhost:9999/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:9999/me

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://product-service-db:3306/product_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

#security:
#  oauth2:
#    client:
#      client-id: shopify
#      client-secret: shopify
#      access-token-uri: http://localhost:9999/oauth/token
#      user-authorization-uri: http://localhost:9999/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:9999/me

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/