spring:
  application:
    name: bff
  profiles:
    active: local

server:
  port: 8080
  context-path: /shopify

security:
  oauth2:
    client:
      client-id: shopify
      client-secret: shopify
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/me

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

---
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/